#pragma once

#include "main.h"
#include "./imgs/0.h"
#include "./imgs/1.h"
#include "./imgs/10.h"
#include "./imgs/11.h"
#include "./imgs/12.h"
#include "./imgs/13.h"
#include "./imgs/14.h"
#include "./imgs/15.h"
#include "./imgs/16.h"
#include "./imgs/17.h"
#include "./imgs/18.h"
#include "./imgs/19.h"
#include "./imgs/2.h"
#include "./imgs/20.h"
#include "./imgs/21.h"
#include "./imgs/22.h"
#include "./imgs/23.h"
#include "./imgs/24.h"
#include "./imgs/25.h"
#include "./imgs/26.h"
#include "./imgs/27.h"
#include "./imgs/28.h"
#include "./imgs/29.h"
#include "./imgs/3.h"
#include "./imgs/30.h"
#include "./imgs/31.h"
#include "./imgs/32.h"
#include "./imgs/33.h"
#include "./imgs/34.h"
#include "./imgs/35.h"
#include "./imgs/36.h"
#include "./imgs/37.h"
#include "./imgs/38.h"
#include "./imgs/39.h"
#include "./imgs/4.h"
#include "./imgs/40.h"
#include "./imgs/41.h"
#include "./imgs/42.h"
#include "./imgs/43.h"
#include "./imgs/44.h"
#include "./imgs/45.h"
#include "./imgs/46.h"
#include "./imgs/47.h"
#include "./imgs/48.h"
#include "./imgs/49.h"
#include "./imgs/5.h"
#include "./imgs/50.h"
#include "./imgs/51.h"
#include "./imgs/52.h"
#include "./imgs/53.h"
#include "./imgs/54.h"
#include "./imgs/55.h"
#include "./imgs/56.h"
#include "./imgs/57.h"
#include "./imgs/58.h"
#include "./imgs/59.h"
#include "./imgs/6.h"
#include "./imgs/60.h"
#include "./imgs/61.h"
#include "./imgs/62.h"
#include "./imgs/63.h"
#include "./imgs/64.h"
#include "./imgs/65.h"
#include "./imgs/66.h"
#include "./imgs/67.h"
#include "./imgs/68.h"
#include "./imgs/69.h"
#include "./imgs/7.h"
#include "./imgs/70.h"
#include "./imgs/71.h"
#include "./imgs/72.h"
#include "./imgs/73.h"
#include "./imgs/74.h"
#include "./imgs/75.h"
#include "./imgs/76.h"
#include "./imgs/77.h"
#include "./imgs/78.h"
#include "./imgs/79.h"
#include "./imgs/8.h"
#include "./imgs/80.h"
#include "./imgs/81.h"
#include "./imgs/82.h"
#include "./imgs/83.h"
#include "./imgs/84.h"
#include "./imgs/85.h"
#include "./imgs/86.h"
#include "./imgs/87.h"
#include "./imgs/88.h"
#include "./imgs/89.h"
#include "./imgs/9.h"
#include "./imgs/90.h"
#include "./imgs/91.h"
#include "./imgs/92.h"
#include "./imgs/93.h"
#include "./imgs/94.h"
#include "./imgs/95.h"
#include "./imgs/96.h"
#include "./imgs/97.h"
#include "./imgs/98.h"
#include "./imgs/99.h"
#include "./imgs/a.h"
#include "./imgs/black.h"
#include "./imgs/blue.h"
#include "./imgs/dislike.h"
#include "./imgs/down_green.h"
#include "./imgs/down_red.h"
#include "./imgs/e.h"
#include "./imgs/g.h"
#include "./imgs/green.h"
#include "./imgs/left_green.h"
#include "./imgs/left_red.h"
#include "./imgs/light_blue.h"
#include "./imgs/like.h"
#include "./imgs/m.h"
#include "./imgs/no.h"
#include "./imgs/o.h"
#include "./imgs/orange.h"
#include "./imgs/red.h"
#include "./imgs/right_green.h"
#include "./imgs/right_red.h"
#include "./imgs/up_green.h"
#include "./imgs/up_red.h"
#include "./imgs/v.h"
#include "./imgs/x.h"
#include "./imgs/yellow.h"

const uint32_t *GetImage(uint8_t imgCode) {
  switch (imgCode) {
  case 0:
    return _0;
  case 1:
    return _1;
  case 2:
    return _2;
  case 3:
    return _3;
  case 4:
    return _4;
  case 5:
    return _5;
  case 6:
    return _6;
  case 7:
    return _7;
  case 8:
    return _8;
  case 9:
    return _9;
  case 10:
    return _10;
  case 11:
    return _11;
  case 12:
    return _12;
  case 13:
    return _13;
  case 14:
    return _14;
  case 15:
    return _15;
  case 16:
    return _16;
  case 17:
    return _17;
  case 18:
    return _18;
  case 19:
    return _19;
  case 20:
    return _20;
  case 21:
    return _21;
  case 22:
    return _22;
  case 23:
    return _23;
  case 24:
    return _24;
  case 25:
    return _25;
  case 26:
    return _26;
  case 27:
    return _27;
  case 28:
    return _28;
  case 29:
    return _29;
  case 30:
    return _30;
  case 31:
    return _31;
  case 32:
    return _32;
  case 33:
    return _33;
  case 34:
    return _34;
  case 35:
    return _35;
  case 36:
    return _36;
  case 37:
    return _37;
  case 38:
    return _38;
  case 39:
    return _39;
  case 40:
    return _40;
  case 41:
    return _41;
  case 42:
    return _42;
  case 43:
    return _43;
  case 44:
    return _44;
  case 45:
    return _45;
  case 46:
    return _46;
  case 47:
    return _47;
  case 48:
    return _48;
  case 49:
    return _49;
  case 50:
    return _50;
  case 51:
    return _51;
  case 52:
    return _52;
  case 53:
    return _53;
  case 54:
    return _54;
  case 55:
    return _55;
  case 56:
    return _56;
  case 57:
    return _57;
  case 58:
    return _58;
  case 59:
    return _59;
  case 60:
    return _60;
  case 61:
    return _61;
  case 62:
    return _62;
  case 63:
    return _63;
  case 64:
    return _64;
  case 65:
    return _65;
  case 66:
    return _66;
  case 67:
    return _67;
  case 68:
    return _68;
  case 69:
    return _69;
  case 70:
    return _70;
  case 71:
    return _71;
  case 72:
    return _72;
  case 73:
    return _73;
  case 74:
    return _74;
  case 75:
    return _75;
  case 76:
    return _76;
  case 77:
    return _77;
  case 78:
    return _78;
  case 79:
    return _79;
  case 80:
    return _80;
  case 81:
    return _81;
  case 82:
    return _82;
  case 83:
    return _83;
  case 84:
    return _84;
  case 85:
    return _85;
  case 86:
    return _86;
  case 87:
    return _87;
  case 88:
    return _88;
  case 89:
    return _89;
  case 90:
    return _90;
  case 91:
    return _91;
  case 92:
    return _92;
  case 93:
    return _93;
  case 94:
    return _94;
  case 95:
    return _95;
  case 96:
    return _96;
  case 97:
    return _97;
  case 98:
    return _98;
  case 99:
    return _99;
  case 100:
    return no;
  case 101:
    return x;
  case 102:
    return like;
  case 103:
    return dislike;
  case 104:
    return red;
  case 105:
    return green;
  case 106:
    return blue;
  case 107:
    return a;
  case 108:
    return e;
  case 109:
    return g;
  case 110:
    return m;
  case 111:
    return o;
  case 112:
    return v;
  case 113:
    return down_red;
  case 114:
    return down_green;
  case 115:
    return up_green;
  case 116:
    return up_red;
  case 117:
    return left_green;
  case 118:
    return left_red;
  case 119:
    return right_green;
  case 120:
    return right_red;
  case 255:
    return black;
  default:
    return NULL;
  }
}